id: I333D9BD1
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T09:00:15+00:00'
last_modified: '2022-06-08T03:21:55.564282+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W28832
  title: སློབ་རའི་གཏམ་ཚོགས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    885F:
      image_group_id: I1PD28104
      title: ''
      total_pages: 294
      order: 1
      base_file: 885F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
