id: P005477
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 11:52:38.258941
source_metadata:
  id: bdr:W28832
  title: སློབ་རའི་གཏམ་ཚོགས
  author: ''
  volumes:
    8beb11db9722472a814e9bb0419afdc5:
      image_group_id: I1PD28104
      title: ''
      volume_number: 1
      total_pages: 294
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
